# Generated by Django 3.1.3 on 2020-12-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(max_length=30),
        ),
    ]
